# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0004_auto_20161021_0558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coral_code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coral_code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
