# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20161102_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='destination_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='hotel_code',
            field=models.CharField(max_length=100),
        ),
    ]
