# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 07:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20161102_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='user',
        ),
        migrations.DeleteModel(
            name='Bookings',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
